config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sessions, only: %i[new]
  resources :streams,  only: %i[index show]
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_code.rb
class CheckCode < ApplicationRecord
  before_validation :generate
  validates :code, presence: true

  def generate
    self.code = SecureRandom.uuid
  end
end

app/models/session.rb
class Session < ApplicationRecord
  attr_accessor :code

  validates :token, presence: true

  def data
    super ? OpenStruct.new(super) : nil
  end

  def token
    data&.access_token
  end

  def refresh_token
    data&.refresh_token
  end

  def expires_in
    data&.expires_in&.to_i&.seconds
  end
end

app/models/stream.rb
class Stream < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActionController::ParameterMissing, with: :bad_request
  rescue_from ActiveRecord::RecordInvalid, with: :unprocessable_request
  rescue_from ::Twitch::AuthorizeService::UnauthorizedException, with: :unauthorized_request

  def bad_request
    render file: 'public/400.html', status: :bad_request, layout: false
  end

  def unauthorized_request
    render file: 'public/400.html', status: :unauthorized, layout: false
  end

  def unprocessable_request
    render file: 'public/422.html', status: :unprocessable_entity, layout: false
  end

  def require_session
    return unless invalid_session?
    
    check = CheckCode.create!
    redirect_to ::Twitch::AuthorizeService.url(check.code)
  end

  def invalid_session?
    current_session.blank? ||
      ::Sessions::Manage.call({ session: current_session, cookies: session }).error.present?
  end

  def current_session
    @current_session ||= Session.find_by(id: session[:_session_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    sessions_params
    ::Sessions::Authenticate.call(sessions_params).error
    redirect_to streams_path
  end

  def code
    value = params[:code].presence
    raise ::Twitch::AuthorizeService::UnauthorizedException.new('unauthorized request') unless value

    value
  end

  def sessions_params
    new_session = Session.new(code: code)
    { session: new_session, check: params[:state], cookies: session }
  end
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  before_action :require_session

  def index
    @streams = {}
    @streams = channels_list if params[:q].present?
  end

  def show
    @stream = stream.body.dig('data', 0)
  end

  private

  def channels_service
    ::Twitch::ChannelsService.new(current_session)
  end

  def stream
    channels_service.details(params.require(:id)).tap do |response|
      raise ActiveRecord::RecordNotFound unless response.success?
    end
  end

  def channels_list
    channels_service.search(params[:q]).body['data']
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to streams_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitchOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/streams/index.html.erb
<%= form_tag(streams_path, method: :get) do |form| %>
  <%= text_field_tag :q, params[:q] %>
  <%= submit_tag "Search" %>
<% end %>
<% if @streams.any? %>
  <table>
    <th>
      <td>Name</td>
      <td>Is live</td>
      <td></td>
    </th>
    <% @streams.each do |stream| %>
      <tr>
        <td><%= stream['display_name'] %></td>
        <td><%= image_tag stream['thumbnail_url'], width: 30 %></td>
        <td><%= link_to "View", stream_path(id: stream['id']), data: { turbolinks: false }%></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/streams/show.html.erb
<%= link_to  "go back", streams_path %>
<div id="twitch-embed"></div>
<script src="https://embed.twitch.tv/embed/v1.js"></script>
<script type="text/javascript">
  new Twitch.Embed("twitch-embed", { width: 854, height: 480, channel: '<%= @stream['display_name'] %>' });
</script>

app/views/welcome/index.html.erb
Welcome Page